In [7]:
import numpy as np
import time

np.random.seed(42)

print("numpy version:", np.__version__)

numpy version: 2.4.6


In [8]:
prices= list(range(1, 1_000_001))

start= time.time()
discounted_loop= [p* 0.95 for p in prices]
loop_time= time.time() - start
print(f"Loop version: {loop_time: .4f}seconds")

prices_np= np.arange(1, 1_000_001)

start= time.time()
discounted_np= prices_np*0.95
np_time= time.time() - start
print(f"NumPy version: {np_time: .4f} seconds")

print( f"NumPy was about {loop_time / np_time :.0f} x faster")

Loop version:  0.2045seconds
NumPy version:  0.0102 seconds
NumPy was about 20 x faster


In [9]:
a = np.array([10,20,30,40])
zeros= np.zeros((2,3))
ones= np.ones((3,3))
seq= np.arange(0,10,2)
lin= np.linspace(0,1,5)

ones= np.ones((3,3))
seq= np.arange(0,10,2)
lin= np.linspace(0,1,5)

print("a:", a)
print("zeros:\n", zeros)
print("ones:\n", ones)
print("seq:", seq)
print("lin:", lin)

a: [10 20 30 40]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
seq: [0 2 4 6 8]
lin: [0.   0.25 0.5  0.75 1.  ]
